// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TheMatrix2/Bookstore-Info-System/backend/internal/interfaces (interfaces: AuthorServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/dto"
	models "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuthorServiceInterface is a mock of AuthorServiceInterface interface.
type MockAuthorServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorServiceInterfaceMockRecorder
}

// MockAuthorServiceInterfaceMockRecorder is the mock recorder for MockAuthorServiceInterface.
type MockAuthorServiceInterfaceMockRecorder struct {
	mock *MockAuthorServiceInterface
}

// NewMockAuthorServiceInterface creates a new mock instance.
func NewMockAuthorServiceInterface(ctrl *gomock.Controller) *MockAuthorServiceInterface {
	mock := &MockAuthorServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthorServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorServiceInterface) EXPECT() *MockAuthorServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthorServiceInterface) Create(arg0 context.Context, arg1 dto.AuthorInput) (*models.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthorServiceInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorServiceInterface)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockAuthorServiceInterface) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthorServiceInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthorServiceInterface)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockAuthorServiceInterface) GetAll(arg0 context.Context) ([]models.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]models.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAuthorServiceInterfaceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAuthorServiceInterface)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockAuthorServiceInterface) GetByID(arg0 context.Context, arg1 uuid.UUID) (*models.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuthorServiceInterfaceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuthorServiceInterface)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockAuthorServiceInterface) Update(arg0 context.Context, arg1 uuid.UUID, arg2 dto.AuthorInput) (*models.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAuthorServiceInterfaceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthorServiceInterface)(nil).Update), arg0, arg1, arg2)
}
