// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TheMatrix2/Bookstore-Info-System/backend/internal/interfaces (interfaces: PublisherServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/dto"
	models "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPublisherServiceInterface is a mock of PublisherServiceInterface interface.
type MockPublisherServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherServiceInterfaceMockRecorder
}

// MockPublisherServiceInterfaceMockRecorder is the mock recorder for MockPublisherServiceInterface.
type MockPublisherServiceInterfaceMockRecorder struct {
	mock *MockPublisherServiceInterface
}

// NewMockPublisherServiceInterface creates a new mock instance.
func NewMockPublisherServiceInterface(ctrl *gomock.Controller) *MockPublisherServiceInterface {
	mock := &MockPublisherServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPublisherServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherServiceInterface) EXPECT() *MockPublisherServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublisherServiceInterface) Create(arg0 context.Context, arg1 dto.PublisherInput) (*models.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*models.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPublisherServiceInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublisherServiceInterface)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPublisherServiceInterface) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPublisherServiceInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublisherServiceInterface)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockPublisherServiceInterface) GetAll(arg0 context.Context) ([]models.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]models.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPublisherServiceInterfaceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPublisherServiceInterface)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockPublisherServiceInterface) GetByID(arg0 context.Context, arg1 uuid.UUID) (*models.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPublisherServiceInterfaceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPublisherServiceInterface)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockPublisherServiceInterface) Update(arg0 context.Context, arg1 uuid.UUID, arg2 dto.PublisherInput) (*models.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPublisherServiceInterfaceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublisherServiceInterface)(nil).Update), arg0, arg1, arg2)
}
