// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TheMatrix2/Bookstore-Info-System/backend/internal/interfaces (interfaces: AuthorRepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuthorRepositoryInterface is a mock of AuthorRepositoryInterface interface.
type MockAuthorRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorRepositoryInterfaceMockRecorder
}

// MockAuthorRepositoryInterfaceMockRecorder is the mock recorder for MockAuthorRepositoryInterface.
type MockAuthorRepositoryInterfaceMockRecorder struct {
	mock *MockAuthorRepositoryInterface
}

// NewMockAuthorRepositoryInterface creates a new mock instance.
func NewMockAuthorRepositoryInterface(ctrl *gomock.Controller) *MockAuthorRepositoryInterface {
	mock := &MockAuthorRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuthorRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorRepositoryInterface) EXPECT() *MockAuthorRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthorRepositoryInterface) Create(arg0 context.Context, arg1 *models.Author) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthorRepositoryInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorRepositoryInterface)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockAuthorRepositoryInterface) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthorRepositoryInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthorRepositoryInterface)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockAuthorRepositoryInterface) GetAll(arg0 context.Context) ([]models.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]models.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAuthorRepositoryInterfaceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAuthorRepositoryInterface)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockAuthorRepositoryInterface) GetByID(arg0 context.Context, arg1 uuid.UUID) (*models.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuthorRepositoryInterfaceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuthorRepositoryInterface)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockAuthorRepositoryInterface) Update(arg0 context.Context, arg1 *models.Author) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuthorRepositoryInterfaceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthorRepositoryInterface)(nil).Update), arg0, arg1)
}
