// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TheMatrix2/Bookstore-Info-System/backend/internal/interfaces (interfaces: PublisherRepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPublisherRepositoryInterface is a mock of PublisherRepositoryInterface interface.
type MockPublisherRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherRepositoryInterfaceMockRecorder
}

// MockPublisherRepositoryInterfaceMockRecorder is the mock recorder for MockPublisherRepositoryInterface.
type MockPublisherRepositoryInterfaceMockRecorder struct {
	mock *MockPublisherRepositoryInterface
}

// NewMockPublisherRepositoryInterface creates a new mock instance.
func NewMockPublisherRepositoryInterface(ctrl *gomock.Controller) *MockPublisherRepositoryInterface {
	mock := &MockPublisherRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPublisherRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherRepositoryInterface) EXPECT() *MockPublisherRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublisherRepositoryInterface) Create(arg0 context.Context, arg1 *models.Publisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPublisherRepositoryInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublisherRepositoryInterface)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPublisherRepositoryInterface) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPublisherRepositoryInterfaceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublisherRepositoryInterface)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockPublisherRepositoryInterface) GetAll(arg0 context.Context) ([]models.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]models.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPublisherRepositoryInterfaceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPublisherRepositoryInterface)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockPublisherRepositoryInterface) GetByID(arg0 context.Context, arg1 uuid.UUID) (*models.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPublisherRepositoryInterfaceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPublisherRepositoryInterface)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockPublisherRepositoryInterface) Update(arg0 context.Context, arg1 *models.Publisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPublisherRepositoryInterfaceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublisherRepositoryInterface)(nil).Update), arg0, arg1)
}
