// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/TheMatrix2/Bookstore-Info-System/backend/internal/interfaces (interfaces: JWTServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	interfaces "github.com/TheMatrix2/Bookstore-Info-System/backend/internal/interfaces"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockJWTServiceInterface is a mock of JWTServiceInterface interface.
type MockJWTServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJWTServiceInterfaceMockRecorder
}

// MockJWTServiceInterfaceMockRecorder is the mock recorder for MockJWTServiceInterface.
type MockJWTServiceInterfaceMockRecorder struct {
	mock *MockJWTServiceInterface
}

// NewMockJWTServiceInterface creates a new mock instance.
func NewMockJWTServiceInterface(ctrl *gomock.Controller) *MockJWTServiceInterface {
	mock := &MockJWTServiceInterface{ctrl: ctrl}
	mock.recorder = &MockJWTServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTServiceInterface) EXPECT() *MockJWTServiceInterfaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockJWTServiceInterface) GenerateToken(arg0 uuid.UUID, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJWTServiceInterfaceMockRecorder) GenerateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJWTServiceInterface)(nil).GenerateToken), arg0, arg1)
}

// ValidateToken mocks base method.
func (m *MockJWTServiceInterface) ValidateToken(arg0 string) (*interfaces.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0)
	ret0, _ := ret[0].(*interfaces.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockJWTServiceInterfaceMockRecorder) ValidateToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJWTServiceInterface)(nil).ValidateToken), arg0)
}
